# Generated by Django 5.2.8 on 2025-11-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_contact_number_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cluster',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
