# Generated by Django 5.2.8 on 2025-11-24 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_cluster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cluster',
        ),
    ]
